config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :tweets do
    resources :comments
  end
  root "tweets#index"
  resources :friend_requests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
    belongs_to :user
    belongs_to :request, class_name: 'User'
    validates :user_id, uniqueness: { scope: :request_id }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, length: { minimum: 3}
  validates :name, presence: true, length: { minimum: 3}
  has_many :tweets
  has_many :comments
  has_many :friend_requests
  has_many :requests, foreign_key: 'request_id', class_name: 'FriendRequest'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @tweet = Tweet.find(params[:tweet_id])
        @comment = @tweet.comments.create(comment_params)
        
        redirect_to root_path
    end

    private
    def comment_params
        params.require(:comment).permit(:body, :user_id)
    end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController

    

    def create
        @friend_request = current_user.friend_requests.new(friend_request_params)
        respond_to do |format|
            if @friend_request.save
                format.html { redirect_to root_path }
            else
                format.html { redirect_to root_path }
            end
        end
    end

    private
    def friend_request_params
        params.require(:friend_request).permit(:request_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters, if: :devise_controller?
    private
    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation) 
    end
    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password) 
    end
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:user, keys: [:name, :username, :email, :password, :password_confirmation])
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
    @users = User.all
    @list = current_user.friend_requests.map { |fr| fr.request_id } if user_signed_in?
  end

  # GET /tweets/1 or /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to root_path }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.comments.destroy_all
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [@tweet, @tweet.comments.build ] do |form| %>
    <div>
        <%= form.text_area :body%>
        <input type="hidden" name="comment[user_id]" value="<%= current_user.id %>">
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitty</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <div>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete%>
      </div>
      <p>Currently logged in:</p>
      <%= current_user.email %>
    <% else %>
      <div>
        <%= link_to "Sign In", new_user_session_path%>
      </div>
      <div>
        <%= link_to "Sign up", new_user_registration_path%>
      </div>
    <% end %>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with model: tweet do |form| %>
  <div>
    <%= form.text_area :body%>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>
<% if user_signed_in?%>
  <%= render 'users/user_index'%>
<% end %>
<h1>Tweets</h1>
<% if user_signed_in? %>
  <%= render "form", tweet: @tweet %>
<% end %>
<div id="tweets">
  <p> Tweets: </p>
  <% @tweets.each do |tweet| %>
    <%= tweet.user.name %><br>
    @<%= tweet.user.username %><br>
    <%= tweet.body %><br>
    <p>comments:</p>
    <% tweet.comments.each do |comment| %>
      <%= comment.body %><br>
    <% end %>
    
    <% if user_signed_in?%>
      <%= link_to "Comment", tweet_path(tweet) %><br>
    <% end %>
        
        <% if user_signed_in? %>
          <% if current_user.email == tweet.user.email %>
          <%= link_to "Edit Tweet", edit_tweet_path(tweet)%>
          <%= link_to "Delete Tweet", tweet_path(tweet), data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure" } %><br>
          <% end %>
        <% end %>
    
  <% end %>
  <%= render @tweet.comments %>
</div>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= @tweet.body %>

<div>
  <%= link_to "Back to tweets", root_path%>
</div>

<div>
  <%= render "comments/form" %>
</div>

app/views/users/_user.html.erb
<div class="user_request">
    <div>
        <%= user.name %>
        <%= user.username %>
    </div>
   
    <div class="request_button">
        <%= form_with(url: friend_requests_path, method: 'post') do %>
            <input type="hidden" name="friend_request[request_id]" value="<%= user.id %>" autocomplete="off">
            <%= submit_tag("Add", class: "btn") %>
        <% end %>
    </div>
    
</div>

app/views/users/_user_index.html.erb
<% @users.each do |user| %>
    
    <%if current_user != user && @list.exclude?(user.id) %>
        <%= render user %>
    <% end %>

<% end %>